# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 362)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.editButton = QtWidgets.QToolButton(self.centralwidget)
        self.editButton.setObjectName("editButton")
        self.gridLayout.addWidget(self.editButton, 0, 0, 1, 1)
        self.guessButton = QtWidgets.QToolButton(self.centralwidget)
        self.guessButton.setObjectName("guessButton")
        self.gridLayout.addWidget(self.guessButton, 0, 1, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.gridLayout.addWidget(self.treeWidget, 1, 0, 2, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ansLabel = QtWidgets.QLabel(self.centralwidget)
        self.ansLabel.setObjectName("ansLabel")
        self.horizontalLayout.addWidget(self.ansLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.delAButton = QtWidgets.QPushButton(self.centralwidget)
        self.delAButton.setObjectName("delAButton")
        self.horizontalLayout.addWidget(self.delAButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.ansListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.ansListWidget.setAlternatingRowColors(True)
        self.ansListWidget.setObjectName("ansListWidget")
        self.gridLayout.addWidget(self.ansListWidget, 2, 1, 1, 1)
        self.qListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.qListWidget.setAlternatingRowColors(True)
        self.qListWidget.setObjectName("qListWidget")
        self.gridLayout.addWidget(self.qListWidget, 2, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.qsLabel = QtWidgets.QLabel(self.centralwidget)
        self.qsLabel.setObjectName("qsLabel")
        self.horizontalLayout_2.addWidget(self.qsLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.addAButton = QtWidgets.QToolButton(self.centralwidget)
        self.addAButton.setObjectName("addAButton")
        self.horizontalLayout_2.addWidget(self.addAButton)
        self.addQButton = QtWidgets.QToolButton(self.centralwidget)
        self.addQButton.setObjectName("addQButton")
        self.horizontalLayout_2.addWidget(self.addQButton)
        self.delQButton = QtWidgets.QToolButton(self.centralwidget)
        self.delQButton.setObjectName("delQButton")
        self.horizontalLayout_2.addWidget(self.delQButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.editButton.setText(_translate("MainWindow", "Editer l\'arbre"))
        self.guessButton.setText(_translate("MainWindow", "Deviner à partir de réponses"))
        self.ansLabel.setText(_translate("MainWindow", "Réponses"))
        self.delAButton.setText(_translate("MainWindow", "Supprimer"))
        self.qsLabel.setText(_translate("MainWindow", "Toutes les questions"))
        self.addAButton.setText(_translate("MainWindow", "<"))
        self.addQButton.setText(_translate("MainWindow", "+"))
        self.delQButton.setText(_translate("MainWindow", "-"))

